### ISSUE TITLE
No salt?

### ISSUE THREAD

**Issue by ORBAT** [unix4fun/naclpipe#2]
Shouldn't scrypt always be used with a random salt? You currently create an [empty salt](https://github.com/unix4fun/naclpipe/blob/9ed1272c5a0fb1eae1493e47c7404b9e5e3ff0be/crypto.go#L45-L48) slice each time.

**Comment by eau-u4f** [comment]
well, salt should be a command line parameter really, otherwise how can you stretch/derivate the same key on the other side for decryption without the same salt?
(i intentionally left it blank as to avoid adding one command parameter, but as said, it should probably be a parameter)

I also need to test on large data and commit the unit testing of the functions so that i can say it's clean/reliable, it was really done quickly :)

thanks for reporting.

**Comment by ORBAT** [comment]
Usually the salt isn't a user-provided parameter. One common way to do it is to generate it (using a CSPRNG) and then append it (in cleartext) to the ciphertext blob (the salt isn't a secret.) Then when you read the file, you first read the _N_ bytes of salt, and then the rest of the ciphertext.

The important thing is that it _must_ be unique per generated key

**Comment by eau-u4f** [comment]
yes, obviously the salt is not a secret.
true, as in modern unix password files, I should have proposed to prefix it to the ciphertext thanks for reminder, will fix that today, thank for the report.

**Comment by eau-u4f** [comment]
now fixed.

**Comment by eau-u4f** [comment]
now fixed
